import {
  Activity,
  AlertTriangle,
  Award,
  Banknote,
  BedDouble,
  Bell,
  BookCheck,
  BookMarked,
  BookOpen,
  Boxes,
  Briefcase,
  Building2,
  Bus,
  CalendarClock,
  CalendarDays,
  ClipboardCheck,
  ClipboardList,
  ClipboardPen,
  Contact,
  CreditCard,
  DoorOpen,
  FileBadge,
  FileCheck,
  FileSpreadsheet,
  FileText,
  FolderOpen,
  Gavel,
  GraduationCap,
  HandCoins,
  Handshake,
  Home,
  IdCard,
  Landmark,
  LayoutDashboard,
  Library,
  type LucideIcon,
  Megaphone,
  MessageSquare,
  Package,
  Plane,
  Receipt,
  Route,
  School,
  ScrollText,
  Settings,
  ShieldCheck,
  Signature,
  SlidersHorizontal,
  Table2,
  Timer,
  TrendingUp,
  Trophy,
  Truck,
  UserCheck,
  UserCog,
  UserPlus,
  Users,
  Wallet,
  Wrench,
} from 'lucide-react';

/**
 * Nav icons are looked up by *name*, not passed as components.
 *
 * `lib/dashboard-pages.tsx` builds each dashboard's nav list in a Server
 * Component and hands it to the client shells as a prop — a React component
 * reference is not serializable across that boundary, so NavItem stores a
 * string key and the client sidebar resolves it here. Adding an icon means
 * adding it to this map; the `NavIconName` union then makes a typo in a nav
 * entry a compile error rather than a missing glyph at runtime.
 */
export const NAV_ICONS = {
  activity: Activity,
  alert: AlertTriangle,
  award: Award,
  banknote: Banknote,
  bed: BedDouble,
  bell: Bell,
  bookCheck: BookCheck,
  bookMarked: BookMarked,
  bookOpen: BookOpen,
  boxes: Boxes,
  briefcase: Briefcase,
  building: Building2,
  bus: Bus,
  calendar: CalendarDays,
  calendarClock: CalendarClock,
  clipboardCheck: ClipboardCheck,
  clipboardList: ClipboardList,
  clipboardPen: ClipboardPen,
  contact: Contact,
  creditCard: CreditCard,
  doorOpen: DoorOpen,
  fileBadge: FileBadge,
  fileCheck: FileCheck,
  fileSpreadsheet: FileSpreadsheet,
  fileText: FileText,
  folder: FolderOpen,
  gavel: Gavel,
  graduationCap: GraduationCap,
  handCoins: HandCoins,
  handshake: Handshake,
  home: Home,
  idCard: IdCard,
  landmark: Landmark,
  layoutDashboard: LayoutDashboard,
  library: Library,
  megaphone: Megaphone,
  messageSquare: MessageSquare,
  package: Package,
  plane: Plane,
  receipt: Receipt,
  route: Route,
  school: School,
  scrollText: ScrollText,
  settings: Settings,
  shieldCheck: ShieldCheck,
  signature: Signature,
  sliders: SlidersHorizontal,
  table: Table2,
  timer: Timer,
  trendingUp: TrendingUp,
  trophy: Trophy,
  truck: Truck,
  userCheck: UserCheck,
  userCog: UserCog,
  userPlus: UserPlus,
  users: Users,
  wallet: Wallet,
  wrench: Wrench,
} satisfies Record<string, LucideIcon>;

export type NavIconName = keyof typeof NAV_ICONS;

// Deliberately no `navIcon(name)` accessor: call sites index NAV_ICONS
// directly. The React Compiler cannot prove an opaque function call returns a
// stable component and rejects `const Icon = navIcon(x); <Icon />` as
// "creating a component during render"; a property read off this constant it
// can follow.
